name: CI-Build-Push-And-Bump

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: cicd-app
  cancel-in-progress: true

jobs:
  build_test_push_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PYTHONPATH: ${{ github.workspace }}   # ← 여기 추가 (리포 루트를 파이썬 모듈 경로로)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps & test
        run: |
          pip install -r requirements.txt pytest
          python -c "import sys,os; print('CWD=',os.getcwd()); print('PYTHONPATH=',os.environ.get('PYTHONPATH')); print('sys.path[0]=',sys.path[0])"
          python -m pytest -q

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cicd-app:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cicd-app:latest

      - name: Bump manifests (dev overlay) to new image SHA
        env:
          MANIFESTS_PAT: ${{ secrets.MANIFESTS_PAT }}
          MANIFESTS_REPO: ${{ secrets.MANIFESTS_REPO }}
          SHA: ${{ github.sha }}
        run: |
          set -e
          git clone https://x-access-token:${MANIFESTS_PAT}@github.com/${MANIFESTS_REPO}.git manifests
          cd manifests/overlays/dev
          sed -i.bak "s#^\(\s*newTag:\s*\).*#\1${SHA}#g" kustomization.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "dev: bump image to ${SHA}"
          git push
